{"uuid":"ff9b527a-9bea-4dee-a625-04ea8e2dae35","historyId":"3d6a19d750661f36fe241f8b298a55b5","fullName":"testClasses.ArrayTests.MaxConsecutiveOnes1","labels":[{"name":"package","value":"testClasses.ArrayTests"},{"name":"testClass","value":"testClasses.ArrayTests"},{"name":"testMethod","value":"MaxConsecutiveOnes1"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"testClasses.ArrayTests"},{"name":"host","value":"Dineshs-MacBook-Pro.local"},{"name":"thread","value":"14095@Dineshs-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"MaxConsecutiveOnes1","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Alert message did not contain expected text. Actual: SyntaxError: bad input on line 2 expected [true] but found [false]","trace":"java.lang.AssertionError: Alert message did not contain expected text. Actual: SyntaxError: bad input on line 2 expected [true] but found [false]\n\tat org.testng.Assert.fail(Assert.java:111)\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\n\tat org.testng.Assert.assertTrue(Assert.java:57)\n\tat testClasses.ArrayTests.MaxConsecutiveOnes1(ArrayTests.java:255)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg2","value":"SyntaxError: bad input on line 1"},{"name":"arg1","value":"3"},{"name":"arg0","value":"pythonCode1"}],"start":1747749663211,"stop":1747749665126}