<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="32" passed="15" failed="17" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-17T00:09:59 EDT" name="MyTestSuite" finished-at="2025-05-17T00:14:02 EDT" duration-ms="243049">
    <groups>
    </groups>
    <test started-at="2025-05-17T00:09:59 EDT" name="ArrayTests" finished-at="2025-05-17T00:14:02 EDT" duration-ms="243049">
      <class name="testClasses.ArrayTests">
        <test-method is-config="true" signature="setUpOnce()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:09:59 EDT" name="setUpOnce" finished-at="2025-05-17T00:10:07 EDT" duration-ms="7690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpOnce -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:07 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:07 EDT" duration-ms="363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysinPython(java.lang.String,int,java.lang.String)[pri:1, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:07 EDT" name="ArraysinPython" data-provider="Pythoncode" finished-at="2025-05-17T00:10:13 EDT" duration-ms="5507" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysinPython -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:13 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:13 EDT" duration-ms="343" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysinPython(java.lang.String,int,java.lang.String)[pri:1, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:13 EDT" name="ArraysinPython" data-provider="Pythoncode" finished-at="2025-05-17T00:10:19 EDT" duration-ms="5949" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.ArraysinPython(ArrayTests.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysinPython -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:19 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:20 EDT" duration-ms="436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysinPython1(java.lang.String,int,java.lang.String)[pri:2, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:20 EDT" name="ArraysinPython1" data-provider="Pythoncode" finished-at="2025-05-17T00:10:31 EDT" duration-ms="11140" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.ArraysinPython1(ArrayTests.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysinPython1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:31 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:31 EDT" duration-ms="398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysinPython1(java.lang.String,int,java.lang.String)[pri:2, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:31 EDT" name="ArraysinPython1" data-provider="Pythoncode" finished-at="2025-05-17T00:10:37 EDT" duration-ms="5946" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysinPython1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:37 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:38 EDT" duration-ms="382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysUsingList(java.lang.String,int,java.lang.String)[pri:3, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:38 EDT" name="ArraysUsingList" data-provider="Pythoncode" finished-at="2025-05-17T00:10:42 EDT" duration-ms="4026" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysUsingList -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:42 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:42 EDT" duration-ms="352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysUsingList(java.lang.String,int,java.lang.String)[pri:3, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:42 EDT" name="ArraysUsingList" data-provider="Pythoncode" finished-at="2025-05-17T00:10:48 EDT" duration-ms="6012" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.ArraysUsingList(ArrayTests.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysUsingList -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:48 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:10:48 EDT" duration-ms="402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysUsingList1(java.lang.String,int,java.lang.String)[pri:4, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:48 EDT" name="ArraysUsingList1" data-provider="Pythoncode" finished-at="2025-05-17T00:10:59 EDT" duration-ms="11032" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.ArraysUsingList1(ArrayTests.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysUsingList1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:10:59 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:00 EDT" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ArraysUsingList1(java.lang.String,int,java.lang.String)[pri:4, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:00 EDT" name="ArraysUsingList1" data-provider="Pythoncode" finished-at="2025-05-17T00:11:06 EDT" duration-ms="6096" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysUsingList1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:06 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:06 EDT" duration-ms="544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="BasicOperationsinLists(java.lang.String,int,java.lang.String)[pri:5, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:06 EDT" name="BasicOperationsinLists" data-provider="Pythoncode" finished-at="2025-05-17T00:11:11 EDT" duration-ms="4604" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasicOperationsinLists -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:11 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:11 EDT" duration-ms="425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="BasicOperationsinLists(java.lang.String,int,java.lang.String)[pri:5, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:11 EDT" name="BasicOperationsinLists" data-provider="Pythoncode" finished-at="2025-05-17T00:11:18 EDT" duration-ms="6214" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.BasicOperationsinLists(ArrayTests.java:133)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasicOperationsinLists -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:18 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:18 EDT" duration-ms="395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="BasicOperationsinLists1(java.lang.String,int,java.lang.String)[pri:6, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:18 EDT" name="BasicOperationsinLists1" data-provider="Pythoncode" finished-at="2025-05-17T00:11:29 EDT" duration-ms="11119" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.BasicOperationsinLists1(ArrayTests.java:144)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasicOperationsinLists1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:29 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:30 EDT" duration-ms="427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="BasicOperationsinLists1(java.lang.String,int,java.lang.String)[pri:6, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:30 EDT" name="BasicOperationsinLists1" data-provider="Pythoncode" finished-at="2025-05-17T00:11:35 EDT" duration-ms="5967" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasicOperationsinLists1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:35 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:36 EDT" duration-ms="446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ApplicationsofArray(java.lang.String,int,java.lang.String)[pri:7, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:36 EDT" name="ApplicationsofArray" data-provider="Pythoncode" finished-at="2025-05-17T00:11:40 EDT" duration-ms="4167" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApplicationsofArray -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:40 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:40 EDT" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ApplicationsofArray(java.lang.String,int,java.lang.String)[pri:7, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:40 EDT" name="ApplicationsofArray" data-provider="Pythoncode" finished-at="2025-05-17T00:11:46 EDT" duration-ms="5936" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.ApplicationsofArray(ArrayTests.java:154)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApplicationsofArray -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:46 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:47 EDT" duration-ms="386" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ApplicationsofArray1(java.lang.String,int,java.lang.String)[pri:8, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:47 EDT" name="ApplicationsofArray1" data-provider="Pythoncode" finished-at="2025-05-17T00:11:58 EDT" duration-ms="11071" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.ApplicationsofArray1(ArrayTests.java:165)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApplicationsofArray1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:58 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:11:58 EDT" duration-ms="338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="ApplicationsofArray1(java.lang.String,int,java.lang.String)[pri:8, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:11:58 EDT" name="ApplicationsofArray1" data-provider="Pythoncode" finished-at="2025-05-17T00:12:04 EDT" duration-ms="6165" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ApplicationsofArray1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:04 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:05 EDT" duration-ms="419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SearchTheArray(java.lang.String,int,java.lang.String)[pri:9, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:05 EDT" name="SearchTheArray" data-provider="Pythoncode1" finished-at="2025-05-17T00:12:09 EDT" duration-ms="4255" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ArrayPracticeQnsQ1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Element Found]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTheArray -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:09 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:09 EDT" duration-ms="455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SearchTheArray(java.lang.String,int,java.lang.String)[pri:9, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:09 EDT" name="SearchTheArray" data-provider="Pythoncode1" finished-at="2025-05-17T00:12:16 EDT" duration-ms="6164" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ArrayPracticeQnsQ1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 2]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.SearchTheArray(ArrayTests.java:195)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTheArray -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:16 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:16 EDT" duration-ms="376" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SearchTheArray1(java.lang.String,int,java.lang.String)[pri:10, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:16 EDT" name="SearchTheArray1" data-provider="Pythoncode1" finished-at="2025-05-17T00:12:27 EDT" duration-ms="11122" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ArrayPracticeQnsQ1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Element Found]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.SearchTheArray1(ArrayTests.java:204)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTheArray1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:27 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:27 EDT" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SearchTheArray1(java.lang.String,int,java.lang.String)[pri:10, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:27 EDT" name="SearchTheArray1" data-provider="Pythoncode1" finished-at="2025-05-17T00:12:34 EDT" duration-ms="6193" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[ArrayPracticeQnsQ1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.SearchTheArray1(ArrayTests.java:204)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTheArray1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:34 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:34 EDT" duration-ms="390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="MaxConsecutiveOnes(java.lang.String,int,java.lang.String)[pri:11, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:34 EDT" name="MaxConsecutiveOnes" data-provider="MaxConsecutiveOnesData" finished-at="2025-05-17T00:12:38 EDT" duration-ms="4182" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MaxConsecutiveOnes -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:38 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:39 EDT" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="MaxConsecutiveOnes(java.lang.String,int,java.lang.String)[pri:11, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:39 EDT" name="MaxConsecutiveOnes" data-provider="MaxConsecutiveOnesData" finished-at="2025-05-17T00:12:45 EDT" duration-ms="6113" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.MaxConsecutiveOnes(ArrayTests.java:212)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MaxConsecutiveOnes -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:45 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:45 EDT" duration-ms="398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="MaxConsecutiveOnes1(java.lang.String,int,java.lang.String)[pri:12, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:45 EDT" name="MaxConsecutiveOnes1" data-provider="MaxConsecutiveOnesData" finished-at="2025-05-17T00:12:57 EDT" duration-ms="11389" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.MaxConsecutiveOnes1(ArrayTests.java:221)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MaxConsecutiveOnes1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:57 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:12:57 EDT" duration-ms="348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="MaxConsecutiveOnes1(java.lang.String,int,java.lang.String)[pri:12, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:12:57 EDT" name="MaxConsecutiveOnes1" data-provider="MaxConsecutiveOnesData" finished-at="2025-05-17T00:13:03 EDT" duration-ms="6098" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MaxConsecutiveOnes1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:03 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:03 EDT" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="EvenNumberOfDigits(java.lang.String,int,java.lang.String)[pri:13, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:03 EDT" name="EvenNumberOfDigits" data-provider="EvenDigitsData" finished-at="2025-05-17T00:13:08 EDT" duration-ms="4200" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[('Count of numbers with even number of digits:', 2)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EvenNumberOfDigits -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:08 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:08 EDT" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="EvenNumberOfDigits(java.lang.String,int,java.lang.String)[pri:13, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:08 EDT" name="EvenNumberOfDigits" data-provider="EvenDigitsData" finished-at="2025-05-17T00:13:14 EDT" duration-ms="6100" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.EvenNumberOfDigits(ArrayTests.java:229)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EvenNumberOfDigits -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:14 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:14 EDT" duration-ms="420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="EvenNumberOfDigits1(java.lang.String,int,java.lang.String)[pri:14, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:14 EDT" name="EvenNumberOfDigits1" data-provider="EvenDigitsData" finished-at="2025-05-17T00:13:26 EDT" duration-ms="11360" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[('Count of numbers with even number of digits:', 2)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.EvenNumberOfDigits1(ArrayTests.java:238)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EvenNumberOfDigits1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:26 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:26 EDT" duration-ms="675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="EvenNumberOfDigits1(java.lang.String,int,java.lang.String)[pri:14, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:26 EDT" name="EvenNumberOfDigits1" data-provider="EvenDigitsData" finished-at="2025-05-17T00:13:33 EDT" duration-ms="6143" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[pythonCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EvenNumberOfDigits1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:33 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:33 EDT" duration-ms="415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SquaresofaSorted(java.lang.String,int,java.lang.String)[pri:15, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:33 EDT" name="SquaresofaSorted" data-provider="Pythoncode" finished-at="2025-05-17T00:13:37 EDT" duration-ms="4188" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SquaresofaSorted -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:37 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:38 EDT" duration-ms="320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SquaresofaSorted(java.lang.String,int,java.lang.String)[pri:15, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:38 EDT" name="SquaresofaSorted" data-provider="Pythoncode" finished-at="2025-05-17T00:13:44 EDT" duration-ms="6148" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SyntaxError: bad input on line 1] but found [Alert: SyntaxError: bad input on line 1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testClasses.ArrayTests.SquaresofaSorted(ArrayTests.java:246)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SquaresofaSorted -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:44 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:44 EDT" duration-ms="415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SquaresofaSorted1(java.lang.String,int,java.lang.String)[pri:16, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:44 EDT" name="SquaresofaSorted1" data-provider="Pythoncode" finished-at="2025-05-17T00:13:55 EDT" duration-ms="11263" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Python is fun!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testClasses.ArrayTests.SquaresofaSorted1(ArrayTests.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SquaresofaSorted1 -->
        <test-method is-config="true" signature="resetToHomeBeforeTest()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:55 EDT" name="resetToHomeBeforeTest" finished-at="2025-05-17T00:13:56 EDT" duration-ms="353" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetToHomeBeforeTest -->
        <test-method signature="SquaresofaSorted1(java.lang.String,int,java.lang.String)[pri:16, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:13:56 EDT" name="SquaresofaSorted1" data-provider="Pythoncode" finished-at="2025-05-17T00:14:02 EDT" duration-ms="6171" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[tryEditorCode]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[SyntaxError: bad input on line 1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SquaresofaSorted1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.ArrayTests@638ef7ed]" started-at="2025-05-17T00:14:02 EDT" name="tearDown" finished-at="2025-05-17T00:14:02 EDT" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.ArrayTests -->
      <class name="baseClass.BaseClass">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:baseClass.BaseClass@238d68ff]" started-at="2025-05-17T00:09:55 EDT" name="SetUp" finished-at="2025-05-17T00:09:59 EDT" duration-ms="3857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:baseClass.BaseClass@238d68ff]" started-at="2025-05-17T00:14:02 EDT" name="tearDown" finished-at="2025-05-17T00:14:02 EDT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- baseClass.BaseClass -->
    </test> <!-- ArrayTests -->
  </suite> <!-- MyTestSuite -->
</testng-results>
